// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/renvo-clarity/Dashboard.tsx": () => import("../components/mockups/renvo-clarity/Dashboard.tsx"),
  "./components/mockups/renvo-command/Dashboard.tsx": () => import("../components/mockups/renvo-command/Dashboard.tsx"),
  "./components/mockups/renvo-enterprise/Dashboard.tsx": () => import("../components/mockups/renvo-enterprise/Dashboard.tsx")
};
